# Hiermit werden die Aufgabenblätter als pdfs und ipynbs gerendert.

project:
  output-dir: _output
  render:
    - Material/Uebungen/Aufgabenblaetter_Strukturen/1A.qmd
    - Material/Uebungen/Aufgabenblaetter_Strukturen/1A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/2A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/2A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/3A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/3A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/4A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/4A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/5A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/5A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/6A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/6A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/7A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/7A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/8A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/8A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/9A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/9A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/10A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/10A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/11A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/11A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/12A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/12A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/13A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/13A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/14A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/14A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/15A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/15A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/16A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/16A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/17A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/17A_sol.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/18A.qmd
    #- Material/Uebungen/Aufgabenblaetter_Strukturen/18A_sol.qmd

format: 
  hsh-exercise-template-pdf: {}
  ipynb: {}
